-- 1
-- SELECT first_name AS "First Name", last_name AS "Last Name" FROM employees;
-- 2
-- SELECT DISTINCT department_id FROM employees;
-- 3
-- SELECT * FROM employees ORDER BY first_name DESC;
-- 4
-- SELECT concat(first_name, ' ', last_name) AS name, salary, concat(salary * .15) AS PF FROM employees;
-- 5
-- SELECT employee_id, concat(first_name, ' ', last_name) AS name, salary FROM employees 
-- ORDER BY salary ASC;
-- 6
-- SELECT SUM(salary) FROM employees;
-- 7 
-- SELECT MAX(salary) AS "Max Salary", MIN(salary) AS "Minimum Salary" FROM employees;
-- 8
-- SELECT AVG(salary) AS "Average Salary" FROM employees;
-- 9
-- SELECT COUNT(*) FROM employees;
-- 10
-- SELECT UPPER(first_name) FROM employees;
-- 11
-- SELECT LEFT(first_name,3) FROM employees;
-- 12 
-- SELECT concat(first_name, ' ', last_name) AS "Full Name" FROM employees;
-- 13
-- SELECT first_name, last_name, LENGTH(concat(first_name,last_name)) FROM employees;
-- 14
-- SELECT first_name FROM employees WHERE first_name ~ '^[0-9]';
-- 15
-- SELECT * FROM employees LIMIT 10;

-- PART 2
-- 1
-- SELECT first_name, last_name FROM employees WHERE salary BETWEEN 10000 AND 15000;
-- 2
-- SELECT first_name, last_name, hire_date FROM employees WHERE EXTRACT(YEAR FROM hire_date) >1987;
-- 3
-- SELECT * FROM employees WHERE first_name ILIKE '%c%' AND first_name ILIKE '%e%'
-- 4
-- SELECT last_name, job_title, salary
-- FROM employees
-- INNER JOIN jobs ON jobs.job_id = employees.job_id
-- WHERE employees.job_id != (SELECT job_id FROM jobs WHERE job_title = 'Programmer')
-- AND employees.job_id != (SELECT job_id FROM jobs WHERE job_title = 'Shipping Clerk')
-- AND salary != 4500
-- AND salary != 10000
-- AND salary != 15000
-- 5
-- SELECT last_name FROM employees WHERE length(last_name) = 6;
-- 6
-- SELECT last_name FROM employees
-- SELECT last_name FROM employees WHERE LEFT(last_name, 3) ='e'
-- 7
-- SELECT DISTINCT job_title FROM employees
-- INNER JOIN jobs ON jobs.job_id = employees.job_id

-- 8
-- SELECT * FROM employees WHERE last_name = 'Jones' 
-- OR last_name = 'Blake'
-- OR last_name = 'Scott'
-- OR last_name = 'King'
-- OR last_name = 'Ford'



